# ZORA MODULE HEADER

"""
Module Name: app
Generated by ZORA SYSTEM – All rights reserved.
ZORA Core Flask Application - Legacy Web Interface
"""

import json
import time
import logging
from datetime import datetime
from flask import Flask, request, jsonify, render_template_string
from flask_cors import CORS

app = Flask(__name__)
CORS(app)  # Enable CORS for all routes

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

WEB_INTERFACE_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZORA CORE - Universal AI Hub</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            margin: 0;
            padding: 20px;
            min-height: 100vh;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 15px;
            padding: 30px;
            backdrop-filter: blur(10px);
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
        }
        .logo {
            font-size: 3em;
            font-weight: bold;
            margin-bottom: 10px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }
        .subtitle {
            font-size: 1.2em;
            opacity: 0.9;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin: 30px 0;
        }
        .stat-card {
            background: rgba(255, 255, 255, 0.15);
            border-radius: 10px;
            padding: 20px;
            text-align: center;
        }
        .stat-number {
            font-size: 2em;
            font-weight: bold;
            color: #FFD700;
        }
        .stat-label {
            font-size: 0.9em;
            opacity: 0.8;
            margin-top: 5px;
        }
        .api-section {
            margin-top: 40px;
            background: rgba(0, 0, 0, 0.2);
            border-radius: 10px;
            padding: 20px;
        }
        .endpoint {
            background: rgba(255, 255, 255, 0.1);
            border-radius: 5px;
            padding: 10px;
            margin: 10px 0;
            font-family: monospace;
        }
        .status-indicator {
            display: inline-block;
            width: 12px;
            height: 12px;
            border-radius: 50%;
            background: #00FF00;
            margin-right: 10px;
            animation: pulse 2s infinite;
        }
        @keyframes pulse {
            0% { opacity: 1; }
            50% { opacity: 0.5; }
            100% { opacity: 1; }
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            opacity: 0.7;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">🌐 ZORA CORE</div>
            <div class="subtitle">Universal AI Hub - Powered by CONNOR × LUMINA × ORACLE</div>
            <div style="margin-top: 15px;">
                <span class="status-indicator"></span>
                <strong>INFINITY MODE ACTIVE</strong>
            </div>
        </div>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-number">24</div>
                <div class="stat-label">AI Agents</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">∞</div>
                <div class="stat-label">Infinity Cycles</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">100%</div>
                <div class="stat-label">System Health</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">{{ uptime }}</div>
                <div class="stat-label">Uptime (seconds)</div>
            </div>
        </div>
        
        <div class="api-section">
            <h3>🔗 API Endpoints</h3>
            <div class="endpoint">GET /api/status - System Status</div>
            <div class="endpoint">GET /api/agents - AI Agent Network</div>
            <div class="endpoint">POST /api/coordination/coordinate - Agent Coordination</div>
            <div class="endpoint">GET /api/infinity/status - Infinity Engine Status</div>
            <div class="endpoint">GET /api/hub/status - Universal Hub Status</div>
            <div class="endpoint">GET /api/monitoring/dashboard - Monitoring Dashboard</div>
            
            <h4 style="margin-top: 20px;">📚 Documentation</h4>
            <div class="endpoint">
                <a href="/docs" style="color: #FFD700; text-decoration: none;">
                    Interactive API Documentation (Swagger UI)
                </a>
            </div>
            <div class="endpoint">
                <a href="/redoc" style="color: #FFD700; text-decoration: none;">
                    Alternative API Documentation (ReDoc)
                </a>
            </div>
        </div>
        
        <div class="footer">
            <p><strong>Founder:</strong> MADS PALLISGAARD</p>
            <p><strong>Version:</strong> 2.0.0 | <strong>Timestamp:</strong> {{ timestamp }}</p>
            <p>🛡️ Ethical AGI • 🔒 Secure • ♾️ Infinite Optimization</p>
        </div>
    </div>
</body>
</html>
"""

@app.before_request
def log_request_info():
    """Log incoming requests"""
    logger.info(f"Flask Request: {request.method} {request.url}")

@app.route('/')
def index():
    """Main web interface"""
    try:
        uptime = int(time.time())
        timestamp = datetime.utcnow().isoformat()
        
        return render_template_string(
            WEB_INTERFACE_TEMPLATE,
            uptime=uptime,
            timestamp=timestamp
        )
    except Exception as e:
        logger.error(f"Web interface error: {e}")
        return f"ZORA CORE WEB INTERFACE ERROR: {str(e)}", 500

@app.route('/status')
def status():
    """JSON status endpoint"""
    return jsonify({
        "status": "operational",
        "message": "ZORA CORE is fully operational – Powered by CONNOR × LUMINA × ORACLE",
        "version": "2.0.0",
        "timestamp": datetime.utcnow().isoformat(),
        "founder": "MADS PALLISGAARD",
        "infinity_mode": True,
        "components": {
            "web_interface": "active",
            "api_system": "active",
            "agent_network": "active",
            "infinity_engine": "active"
        }
    })

@app.route('/health')
def health():
    """Health check endpoint"""
    return jsonify({
        "status": "healthy",
        "timestamp": datetime.utcnow().isoformat(),
        "uptime": time.time(),
        "version": "2.0.0"
    })

@app.route('/api/info')
def api_info():
    """API information endpoint"""
    return jsonify({
        "api_name": "ZORA CORE Flask API",
        "version": "2.0.0",
        "description": "ZORA Core Legacy Web Interface & API",
        "powered_by": ["CONNOR", "LUMINA", "ORACLE"],
        "main_api": {
            "fastapi_server": "Use FastAPI server for full functionality",
            "endpoints": "See /docs for complete API documentation"
        },
        "flask_endpoints": {
            "/": "Web interface",
            "/status": "System status",
            "/health": "Health check",
            "/api/info": "API information"
        },
        "timestamp": datetime.utcnow().isoformat()
    })

@app.route('/docs')
def docs_redirect():
    """Redirect to FastAPI docs"""
    return """
    <html>
    <head>
        <title>ZORA CORE API Documentation</title>
        <meta http-equiv="refresh" content="0; url=http://localhost:8000/docs">
    </head>
    <body>
        <h1>🌐 ZORA CORE API Documentation</h1>
        <p>Redirecting to FastAPI documentation...</p>
        <p>If not redirected automatically, <a href="http://localhost:8000/docs">click here</a></p>
        <p><strong>Note:</strong> Make sure the FastAPI server is running on port 8000</p>
    </body>
    </html>
    """

@app.route('/redoc')
def redoc_redirect():
    """Redirect to FastAPI ReDoc"""
    return """
    <html>
    <head>
        <title>ZORA CORE API Documentation (ReDoc)</title>
        <meta http-equiv="refresh" content="0; url=http://localhost:8000/redoc">
    </head>
    <body>
        <h1>🌐 ZORA CORE API Documentation (ReDoc)</h1>
        <p>Redirecting to FastAPI ReDoc documentation...</p>
        <p>If not redirected automatically, <a href="http://localhost:8000/redoc">click here</a></p>
        <p><strong>Note:</strong> Make sure the FastAPI server is running on port 8000</p>
    </body>
    </html>
    """

@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors"""
    return jsonify({
        "error": "Endpoint not found",
        "message": "This Flask app provides basic web interface. Use FastAPI server for full API functionality.",
        "available_endpoints": ["/", "/status", "/health", "/api/info", "/docs", "/redoc"],
        "timestamp": datetime.utcnow().isoformat()
    }), 404

@app.errorhandler(500)
def internal_error(error):
    """Handle 500 errors"""
    logger.error(f"Internal server error: {error}")
    return jsonify({
        "error": "Internal server error",
        "message": str(error),
        "timestamp": datetime.utcnow().isoformat()
    }), 500

if __name__ == "__main__":
    print("🌐 Starting ZORA Core Flask Web Interface...")
    print("🔗 Web Interface: http://localhost:5000")
    print("📊 Status API: http://localhost:5000/status")
    print("📚 API Info: http://localhost:5000/api/info")
    print("🔧 For full API functionality, use the FastAPI server (zora.py)")
    
    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )

