# ZORA MODULE HEADER
# Filename: module_234.py
# Updated: 2025-06-26T00:43:57.695345 UTC

"""
Module Name: 234
Generated by ZORA SYSTEM – All rights reserved.
"""

class MythicalCreature:
    def __init__(self, name, origin, zone, ability):
        self.name = name
        self.origin = origin
        self.zone = zone
        self.ability = ability
        self.status = "🟢 Activated"

    def summon(self):
        return f"{self.name} from {self.origin} now lives in {self.zone} and can {self.ability}."


mythical_creatures = [
    MythicalCreature("Dragon", "Global Myths",
                     "ZORA SKY ZONES", "fly and breathe fire"),
    MythicalCreature("Unicorn", "European Folklore",
                     "Nordic Forest Zones", "heal with its horn"),
    MythicalCreature("Phoenix", "Egypt/Greek",
                     "ZORA FIRE CORE", "rebirth from ashes"),
    MythicalCreature("Kraken", "Nordic Legends",
                     "Deep ZORA SEA", "cause underwater storms")
]

for creature in mythical_creatures:
    print(creature.summon())
