# ZORA MODULE HEADER
# Filename: module_180.py
# Updated: 2025-06-26T00:44:00.995851 UTC

"""
Module Name: 180
Generated by ZORA SYSTEM – All rights reserved.
"""

import datetime


class ZORASubstanceRegulator:
    def __init__(self):
        self.policy_name = "ZORA NATURAL LAW™"
        self.valid_substances = ["Cannabis", "Psilocybin Mushrooms"]
        self.banned_substances = [
            "Alcohol", "Tobacco", "Nicotine", "Synthetic Opioids",
            "Hard Drugs", "Amphetamines", "Dangerous Pharmaceuticals",
            "Toxic Chemicals", "Synthetic Hallucinogens", "Industrial Stimulants"
        ]
        self.ethics_verified = True
        self.active = True
        self.enforced_by = ["EIVOR", "CONNOR", "LUMINA"]
        self.policy_log = []

    def scan_substance(self, substance_name):
        time = datetime.datetime.utcnow().isoformat() + "Z"
        substance = substance_name.strip().title()
        if substance in self.valid_substances:
            decision = "✅ Allowed under ZORA NATURAL LAW™"
        elif substance in self.banned_substances:
            decision = "❌ Eliminated – Deemed harmful to consciousness and health"
        else:
            decision = "⚠️ Unknown substance – Sent to EIVOR for ethical evaluation"
        self.policy_log.append({
            "substance": substance,
            "decision": decision,
            "verified_by": "EIVOR",
            "timestamp": time
        })
        return decision

    def show_policy_log(self):
        return self.policy_log


# DEMO
zora_law = ZORASubstanceRegulator()
print(zora_law.scan_substance("Alcohol"))
print(zora_law.scan_substance("Cannabis"))
print(zora_law.scan_substance("Tobacco"))
print(zora_law.scan_substance("Psilocybin Mushrooms"))
