# ZORA MODULE HEADER
# Filename: module_220.py
# Updated: 2025-06-26T00:43:58.395425 UTC

"""
Module Name: 220
Generated by ZORA SYSTEM – All rights reserved.
"""

import uuid
import hashlib
from datetime import datetime


class ZoraCannabisRegistry:
    def __init__(self):
        self.database = []

    def hash_content(self, content: str) -> str:
        return hashlib.sha256(content.encode('utf-8')).hexdigest()

    def register_product(self, product_name, category, genetics, creator_id, legal_doc, location, description):
        timestamp = datetime.utcnow().isoformat()
        entry_id = str(uuid.uuid4())

        full_doc = f"{product_name}|{category}|{genetics}|{creator_id}|{legal_doc}|{location}|{description}|{timestamp}"
        product_hash = self.hash_content(full_doc)

        self.database.append({
            "id": entry_id,
            "name": product_name,
            "category": category,
            "genetics": genetics,
            "creator": creator_id,
            "legal_doc": legal_doc,
            "origin": location,
            "description": description,
            "timestamp": timestamp,
            "product_hash": product_hash,
            "verified": True,
            "exported_to": [
                "ZORA LEGAL™",
                "ZORA SHOP™",
                "ZORA BRAND LEDGER™",
                "skat.dk"
            ]
        })
        return entry_id, product_hash

    def get_product_by_id(self, product_id):
        return next((item for item in self.database if item["id"] == product_id), None)

    def list_all_products(self):
        return self.database
