# ZORA MODULE HEADER
# Filename: standard_terminology.py
# Updated: 2025-06-26T00:44:06.213316 UTC

"""
Module Name: standard_terminology
Generated by ZORA SYSTEM – All rights reserved.
"""


# Standard NATO-style military terminology
standard_terms = {
    "copy": "Message received and understood",
    "negative": "No / Refusal",
    "asap": "As Soon As Possible",
    "roger": "Message understood",
    "stand_by": "Await further instructions",
    "affirmative": "Yes / Confirmed",
    "disengage": "Cease current operation",
    "engage": "Initiate operation",
    "hostile": "Identified threat",
    "AO": "Area of Operations",
    "visual": "Target in sight",
    "no_visual": "Target not in sight",
    "tango_down": "Enemy neutralized"
}
