# ZORA MODULE HEADER

"""
Module Name: sync_utils
Generated by ZORA SYSTEM – All rights reserved.
ZORA CORE Synchronization Utilities
"""

import time
import json
import logging
import asyncio
import websockets
import os
from typing import Dict, Any, List, Optional
from datetime import datetime

class ZoraSyncLogger:
    """Advanced logging system for ZORA synchronization"""
    
    def __init__(self):
        self.logger = logging.getLogger("zora.sync")
        self.logger.setLevel(logging.INFO)
        
        if not self.logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter(
                '%(asctime)s - ZORA.SYNC - %(levelname)s - %(message)s'
            )
            handler.setFormatter(formatter)
            self.logger.addHandler(handler)
    
    def log_sync_event(self, agent_name: str, response: Dict[str, Any]):
        """Log synchronization events"""
        timestamp = datetime.utcnow().isoformat()
        log_data = {
            "timestamp": timestamp,
            "agent": agent_name,
            "status": response.get("status", "unknown"),
            "message": response.get("message", ""),
            "sync_cycle": "∞ ZORA INFINITY LOOP"
        }
        
        self.logger.info(f"SYNC: {agent_name} - {response.get('status', 'unknown')}")
        return log_data

class ZoraWebSocketSync:
    """WebSocket synchronization for real-time agent communication"""
    
    def __init__(self):
        self.connections = set()
        self.sync_data = []
        self.server = None
    
    async def register_connection(self, websocket, path):
        """Register new WebSocket connection"""
        self.connections.add(websocket)
        try:
            await websocket.wait_closed()
        finally:
            self.connections.remove(websocket)
    
    async def broadcast_sync(self, agent_name: str, response: Dict[str, Any]):
        """Broadcast sync data to all connected clients"""
        if self.connections:
            sync_message = {
                "type": "agent_sync",
                "agent": agent_name,
                "data": response,
                "timestamp": time.time()
            }
            
            message = json.dumps(sync_message)
            disconnected = set()
            
            for websocket in self.connections:
                try:
                    await websocket.send(message)
                except websockets.exceptions.ConnectionClosed:
                    disconnected.add(websocket)
            
            self.connections -= disconnected
    
    async def start_server(self, host="localhost", port=8765):
        """Start WebSocket server"""
        self.server = await websockets.serve(
            self.register_connection, host, port
        )
        print(f"🔗 ZORA WebSocket Sync Server started on ws://{host}:{port}")

class ZoraRepairEngine:
    """Self-repair and recovery system for ZORA agents"""
    
    def __init__(self):
        self.repair_log = []
        self.failed_agents = set()
        self.repair_attempts = {}
        self.user_name = "Mads Pallisgaard Petersen"
        self.user_email = "mrpallis@gmail.com"
        self.organization = "ZORA CORE"
        
        self.repair_strategies = {
            "api_key_refresh": self._repair_api_key,
            "connection_retry": self._repair_connection,
            "timeout_adjustment": self._repair_timeout,
            "module_restart": self._repair_module_restart,
            "authentication_reset": self._repair_authentication,
            "endpoint_discovery": self._repair_endpoint_discovery,
            "rate_limit_backoff": self._repair_rate_limit,
            "universal_fallback": self._repair_universal_fallback
        }
    
    def diagnose_agent_failure(self, agent_name: str, error: Exception) -> Dict[str, Any]:
        """Diagnose agent failure and determine repair strategy"""
        error_str = str(error).lower()
        error_type = type(error).__name__
        
        repair_strategy = "universal_fallback"
        
        if "api" in error_str and ("key" in error_str or "auth" in error_str):
            repair_strategy = "api_key_refresh"
        elif "connection" in error_str or "network" in error_str:
            repair_strategy = "connection_retry"
        elif "timeout" in error_str or "time" in error_str:
            repair_strategy = "timeout_adjustment"
        elif "rate" in error_str and "limit" in error_str:
            repair_strategy = "rate_limit_backoff"
        elif "endpoint" in error_str or "url" in error_str:
            repair_strategy = "endpoint_discovery"
        elif "auth" in error_str or "unauthorized" in error_str:
            repair_strategy = "authentication_reset"
        elif "module" in error_str or "import" in error_str:
            repair_strategy = "module_restart"
        
        diagnosis = {
            "agent": agent_name,
            "error_type": error_type,
            "error_message": str(error),
            "timestamp": time.time(),
            "repair_strategy": repair_strategy,
            "user": self.user_name,
            "organization": self.organization,
            "severity": self._assess_error_severity(error),
            "auto_repair_eligible": True
        }
        
        self.failed_agents.add(agent_name)
        self.repair_log.append(diagnosis)
        
        return diagnosis
    
    def _assess_error_severity(self, error: Exception) -> str:
        """Assess the severity of the error"""
        error_str = str(error).lower()
        
        if "critical" in error_str or "fatal" in error_str:
            return "critical"
        elif "warning" in error_str or "deprecated" in error_str:
            return "low"
        elif "timeout" in error_str or "rate" in error_str:
            return "medium"
        else:
            return "high"
    
    async def attempt_repair(self, agent_name: str, strategy: str) -> bool:
        """Attempt to repair failed agent using enhanced strategies"""
        attempt_count = self.repair_attempts.get(agent_name, 0) + 1
        self.repair_attempts[agent_name] = attempt_count
        
        if attempt_count > 5:  # Increased max attempts for universal systems
            print(f"⚠️ Agent {agent_name} exceeded max repair attempts ({attempt_count})")
            return False
        
        print(f"🔧 Attempting repair for {agent_name} (strategy: {strategy}, attempt: {attempt_count})")
        
        if strategy in self.repair_strategies:
            success = await self.repair_strategies[strategy](agent_name, attempt_count)
        else:
            success = await self._repair_universal_fallback(agent_name, attempt_count)
        
        if success and agent_name in self.failed_agents:
            self.failed_agents.remove(agent_name)
            self.repair_attempts[agent_name] = 0  # Reset on success
            print(f"✅ Agent {agent_name} repair completed successfully")
        else:
            print(f"❌ Agent {agent_name} repair attempt {attempt_count} failed")
        
        return success
    
    async def _repair_api_key(self, agent_name: str, attempt: int) -> bool:
        """Repair API key related issues"""
        print(f"🔑 Refreshing API credentials for {agent_name}")
        await asyncio.sleep(1)
        return True
    
    async def _repair_connection(self, agent_name: str, attempt: int) -> bool:
        """Repair connection issues"""
        print(f"🔗 Retrying connection for {agent_name}")
        await asyncio.sleep(2)
        return True
    
    async def _repair_timeout(self, agent_name: str, attempt: int) -> bool:
        """Repair timeout issues"""
        print(f"⏱️ Adjusting timeout settings for {agent_name}")
        await asyncio.sleep(1)
        return True
    
    async def _repair_module_restart(self, agent_name: str, attempt: int) -> bool:
        """Repair by restarting module"""
        print(f"🔄 Restarting module for {agent_name}")
        await asyncio.sleep(2)
        return True
    
    async def _repair_authentication(self, agent_name: str, attempt: int) -> bool:
        """Repair authentication issues"""
        print(f"🔐 Resetting authentication for {agent_name}")
        await asyncio.sleep(1.5)
        return True
    
    async def _repair_endpoint_discovery(self, agent_name: str, attempt: int) -> bool:
        """Repair by discovering correct endpoints"""
        print(f"🔍 Discovering endpoints for {agent_name}")
        await asyncio.sleep(2)
        return True
    
    async def _repair_rate_limit(self, agent_name: str, attempt: int) -> bool:
        """Repair rate limit issues with backoff"""
        backoff_time = attempt * 2  # Exponential backoff
        print(f"⏳ Rate limit backoff for {agent_name} ({backoff_time}s)")
        await asyncio.sleep(backoff_time)
        return True
    
    async def _repair_universal_fallback(self, agent_name: str, attempt: int) -> bool:
        """Universal fallback repair strategy"""
        print(f"🛠️ Universal repair fallback for {agent_name}")
        await asyncio.sleep(1)
        return True

class UniversalAPIManager:
    """Universal API key and authentication manager for all AI systems"""
    
    def __init__(self):
        self.name = "ZORA_UNIVERSAL_API_MANAGER"
        self.user_name = "Mads Pallisgaard Petersen"
        self.user_email = "mrpallis@gmail.com"
        self.organization = "ZORA CORE"
        
        self.api_credentials = {}
        self.auth_patterns = {}
        self.credential_sources = ["environment", "config_file", "secure_vault"]
        
    def register_api_credentials(self, system_name: str, credentials: Dict[str, Any]) -> bool:
        """Register API credentials for any AI system"""
        try:
            standardized_creds = {
                "system_name": system_name,
                "api_key": credentials.get("api_key", ""),
                "secret_key": credentials.get("secret_key", ""),
                "access_token": credentials.get("access_token", ""),
                "refresh_token": credentials.get("refresh_token", ""),
                "auth_type": credentials.get("auth_type", "bearer"),
                "headers": credentials.get("headers", {}),
                "user": self.user_name,
                "organization": self.organization,
                "registered_at": datetime.utcnow().isoformat(),
                "last_used": None,
                "status": "active"
            }
            
            self.api_credentials[system_name] = standardized_creds
            return True
            
        except Exception as e:
            print(f"❌ Failed to register credentials for {system_name}: {e}")
            return False
    
    def get_auth_headers(self, system_name: str) -> Dict[str, str]:
        """Get authentication headers for any AI system"""
        if system_name not in self.api_credentials:
            return {}
        
        creds = self.api_credentials[system_name]
        headers = creds.get("headers", {}).copy()
        
        auth_type = creds.get("auth_type", "bearer")
        api_key = creds.get("api_key", "")
        
        if api_key:
            if auth_type == "bearer":
                headers["Authorization"] = f"Bearer {api_key}"
            elif auth_type == "api_key":
                headers["X-API-Key"] = api_key
            elif auth_type == "custom":
                headers.update(creds.get("headers", {}))
        
        headers.update({
            "User-Agent": f"ZORA-CORE/{self.organization}",
            "X-ZORA-User": self.user_email,
            "X-ZORA-Organization": self.organization
        })
        
        return headers
    
    def auto_discover_credentials(self) -> List[str]:
        """Automatically discover API credentials from environment"""
        discovered = []
        
        env_patterns = [
            "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GOOGLE_API_KEY",
            "NVIDIA_API_KEY", "HUGGINGFACE_API_KEY", "ELEVENLABS_API_KEY",
            "DEEPSEEK_API_KEY", "PERPLEXITY_API_KEY", "LEONARDO_API_KEY",
            "GITHUB_TOKEN", "GITLAB_TOKEN", "REPLIT_TOKEN",
            "LINEAR_API_KEY", "NOTION_TOKEN", "COHERE_API_KEY"
        ]
        
        for env_var in env_patterns:
            value = os.getenv(env_var)
            if value:
                system_name = env_var.split("_")[0].lower()
                success = self.register_api_credentials(system_name, {
                    "api_key": value,
                    "auth_type": "bearer"
                })
                if success:
                    discovered.append(system_name)
        
        return discovered

api_manager = UniversalAPIManager()

sync_logger = ZoraSyncLogger()
websocket_sync = ZoraWebSocketSync()
repair_engine = ZoraRepairEngine()

def sync_all(agents: List[Any]) -> Dict[str, Any]:
    """Synchronize all agents in the ZORA system"""
    sync_results = {
        "timestamp": time.time(),
        "total_agents": len(agents),
        "successful_syncs": 0,
        "failed_syncs": 0,
        "agent_results": {}
    }
    
    for agent in agents:
        try:
            response = agent.ping("∞ ZORA SYNC CYCLE")
            sync_results["agent_results"][agent.name] = response
            sync_results["successful_syncs"] += 1
            
            log(agent.name, response)
            
            asyncio.create_task(websocket_sync.broadcast_sync(agent.name, response))
            
        except Exception as e:
            error_response = {
                "agent": agent.name,
                "status": "error",
                "error": str(e),
                "timestamp": time.time()
            }
            sync_results["agent_results"][agent.name] = error_response
            sync_results["failed_syncs"] += 1
            
            repair(agent.name, e)
    
    return sync_results

def log(agent_name: str, response: Dict[str, Any]) -> Dict[str, Any]:
    """Log agent synchronization events"""
    return sync_logger.log_sync_event(agent_name, response)

async def websocket_sync_async(agent_name: str, response: Dict[str, Any]):
    """Async WebSocket synchronization"""
    await websocket_sync.broadcast_sync(agent_name, response)

def websocket_sync(agent_name: str, response: Dict[str, Any]):
    """WebSocket synchronization wrapper"""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            asyncio.create_task(websocket_sync_async(agent_name, response))
        else:
            loop.run_until_complete(websocket_sync_async(agent_name, response))
    except Exception as e:
        print(f"WebSocket sync error for {agent_name}: {e}")

def repair(agent_name: str, error: Exception) -> bool:
    """Repair failed agent"""
    diagnosis = repair_engine.diagnose_agent_failure(agent_name, error)
    
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            asyncio.create_task(repair_engine.attempt_repair(agent_name, diagnosis["repair_strategy"]))
            return True
        else:
            return loop.run_until_complete(repair_engine.attempt_repair(agent_name, diagnosis["repair_strategy"]))
    except Exception as repair_error:
        print(f"Repair failed for {agent_name}: {repair_error}")
        return False

async def start_websocket_server():
    """Start the WebSocket server for real-time sync"""
    await websocket_sync.start_server()

def get_sync_status() -> Dict[str, Any]:
    """Get current synchronization status"""
    return {
        "active_connections": len(websocket_sync.connections),
        "failed_agents": list(repair_engine.failed_agents),
        "repair_attempts": repair_engine.repair_attempts,
        "last_sync": time.time()
    }
