#!/usr/bin/env python3
# ZORA MODULE HEADER

"""
Module Name: test_agimatrix
Generated by ZORA SYSTEM – All rights reserved.
Test AGImatrix LangChain Tool Integration for ZORA CORE
"""

import sys
import os
import json
from datetime import datetime

sys.path.insert(0, '/home/ubuntu/repos/ZORA-CORE')

def test_agimatrix_integration():
    """Test AGImatrix LangChain tool integration"""
    print("🧪 TESTING AGIMATRIX LANGCHAIN INTEGRATION")
    print("=" * 50)
    
    try:
        from AGImatrix import tools, tool_bridge, ZORAUniversalToolBridge
        from AGImatrix import universal_ai_discovery_tool, get_tool_registry_status
        
        print(f"✅ Successfully imported AGImatrix components")
        print(f"📊 Total LangChain tools: {len(tools)}")
        print(f"🔌 Registered APIs: {len(tool_bridge.registered_apis)}")
        
        print(f"\n🌉 Tool Bridge Status:")
        print(f"  Name: {tool_bridge.name}")
        print(f"  User: {tool_bridge.user_name}")
        print(f"  Organization: {tool_bridge.organization}")
        print(f"  Auto-discovery: {tool_bridge.auto_discovery_enabled}")
        
        print(f"\n🔌 Registered AI APIs:")
        for api_name, api_config in tool_bridge.registered_apis.items():
            capabilities = api_config.get('capabilities', [])
            print(f"  ✅ {api_name}: {len(capabilities)} capabilities")
            for cap in capabilities[:2]:  # Show first 2 capabilities
                print(f"    - {cap}")
        
        print(f"\n🔧 LangChain Tools:")
        for i, tool in enumerate(tools[:10]):  # Show first 10 tools
            print(f"  {i+1:2d}. {tool.name}")
            if hasattr(tool, 'description'):
                desc = tool.description[:80] + "..." if len(tool.description) > 80 else tool.description
                print(f"      {desc}")
        
        if len(tools) > 10:
            print(f"  ... and {len(tools) - 10} more tools")
        
        print(f"\n🔍 Testing Universal AI Discovery:")
        discovery_result = universal_ai_discovery_tool("Test discovery query")
        discovery_data = json.loads(discovery_result)
        print(f"  📊 Total registered APIs: {discovery_data.get('total_registered', 0)}")
        print(f"  🆕 Discovered APIs: {len(discovery_data.get('discovered_apis', []))}")
        
        print(f"\n📋 Testing Tool Registry Status:")
        status_result = get_tool_registry_status()
        status_data = json.loads(status_result)
        print(f"  🔧 Total tools: {status_data.get('total_tools', 0)}")
        print(f"  🔌 Registered APIs: {status_data.get('registered_apis', 0)}")
        print(f"  🎯 Total capabilities: {len(status_data.get('capabilities', []))}")
        
        print(f"\n👤 User Profile Integration:")
        user_profile = status_data.get('user_profile', {})
        print(f"  Name: {user_profile.get('name', 'Not Set')}")
        print(f"  Email: {user_profile.get('email', 'Not Set')}")
        print(f"  Organization: {user_profile.get('organization', 'Not Set')}")
        print(f"  Address: {user_profile.get('address', 'Not Set')}")
        print(f"  Phone: {user_profile.get('phone', 'Not Set')}")
        
        print(f"\n🎉 AGIMATRIX INTEGRATION TEST COMPLETED")
        return True
        
    except ImportError as e:
        print(f"❌ Import Error: {e}")
        return False
    except Exception as e:
        print(f"❌ Test Error: {e}")
        return False

def test_tool_functionality():
    """Test individual tool functionality"""
    print(f"\n🔧 TESTING INDIVIDUAL TOOL FUNCTIONALITY")
    print("=" * 50)
    
    try:
        from AGImatrix import tools
        
        test_tools = [
            ("Universal_AI_Discovery", "test query"),
            ("Tool_Registry_Status", ""),
        ]
        
        for tool_name, test_input in test_tools:
            matching_tools = [t for t in tools if t.name == tool_name]
            if matching_tools:
                tool = matching_tools[0]
                print(f"\n🧪 Testing {tool_name}:")
                try:
                    if test_input:
                        result = tool.func(test_input)
                    else:
                        result = tool.func()
                    
                    if len(str(result)) > 200:
                        result_preview = str(result)[:200] + "..."
                    else:
                        result_preview = str(result)
                    
                    print(f"  ✅ Result: {result_preview}")
                    
                except Exception as e:
                    print(f"  ❌ Error: {str(e)}")
            else:
                print(f"  ⚠️ Tool {tool_name} not found")
        
        return True
        
    except Exception as e:
        print(f"❌ Tool Test Error: {e}")
        return False

if __name__ == "__main__":
    print("🚀 ZORA CORE AGIMATRIX TEST SUITE")
    print(f"⏰ Test started at: {datetime.utcnow().isoformat()}Z")
    print()
    
    test1_result = test_agimatrix_integration()
    test2_result = test_tool_functionality()
    
    print("\n" + "=" * 50)
    print("📊 TEST RESULTS SUMMARY:")
    print(f"  AGImatrix Integration: {'✅ PASSED' if test1_result else '❌ FAILED'}")
    print(f"  Tool Functionality: {'✅ PASSED' if test2_result else '❌ FAILED'}")
    
    if test1_result and test2_result:
        print("\n🎉 ALL TESTS PASSED - AGIMATRIX READY FOR ZORA CORE")
    else:
        print("\n⚠️ SOME TESTS FAILED - CHECK INTEGRATION")
    
    print(f"\n⏰ Test completed at: {datetime.utcnow().isoformat()}Z")
