#!/usr/bin/env python3
# ZORA MODULE HEADER

"""
Module Name: test_universal_connector
Generated by ZORA SYSTEM – All rights reserved.
Test Universal AI System Connector Framework for ZORA CORE
"""

import sys
import os
import json
import asyncio
from datetime import datetime

sys.path.insert(0, '/home/ubuntu/repos/ZORA-CORE')

async def test_universal_connector():
    """Test Universal AI Connector Framework"""
    print("🧪 TESTING UNIVERSAL AI CONNECTOR FRAMEWORK")
    print("=" * 50)
    
    try:
        from zora_infinity_sync import universal_connector, UniversalAIConnector
        
        print(f"✅ Successfully imported Universal AI Connector")
        print(f"🔌 Connector Name: {universal_connector.name}")
        print(f"👤 User: {universal_connector.user_name}")
        print(f"🏢 Organization: {universal_connector.organization}")
        
        print(f"\n🔍 Testing Auto-Discovery:")
        discovered = universal_connector.auto_discover_ai_systems()
        print(f"  📊 Discovered {len(discovered)} AI systems")
        for system in discovered[:5]:  # Show first 5
            print(f"    ✅ {system}")
        
        print(f"\n📝 Testing System Registration:")
        test_system = {
            "base_url": "https://api.test-ai.com/v1",
            "auth_type": "bearer",
            "capabilities": ["test_capability", "demo_feature"]
        }
        
        success = universal_connector.register_ai_system("test_ai", test_system)
        print(f"  Registration Success: {'✅' if success else '❌'}")
        
        print(f"\n🔧 Testing Integration Patterns:")
        pattern = universal_connector.create_universal_integration_pattern("test_ai")
        print(f"  Pattern Created: {'✅' if pattern else '❌'}")
        print(f"  Authentication Method: {pattern.get('authentication', {}).get('method', 'N/A')}")
        print(f"  Monitoring Enabled: {pattern.get('monitoring', {}).get('performance_tracking', False)}")
        
        print(f"\n🔗 Testing AI System Connections:")
        test_systems = ["openai", "anthropic", "nvidia", "test_ai"]
        
        for system in test_systems:
            try:
                connected = await universal_connector.connect_to_ai_system(system)
                status = "✅ Connected" if connected else "⚠️ Failed"
                print(f"  {system}: {status}")
            except Exception as e:
                print(f"  {system}: ❌ Error - {e}")
        
        print(f"\n📊 Testing Connector Status:")
        status = universal_connector.get_connector_status()
        print(f"  Total Systems: {status.get('total_registered_systems', 0)}")
        print(f"  Connected Systems: {status.get('connected_systems', 0)}")
        print(f"  Connection Rate: {status.get('connection_rate', 0):.1f}%")
        print(f"  Integration Patterns: {status.get('integration_patterns', 0)}")
        
        print(f"\n🎉 UNIVERSAL CONNECTOR TEST COMPLETED")
        return True
        
    except ImportError as e:
        print(f"❌ Import Error: {e}")
        return False
    except Exception as e:
        print(f"❌ Test Error: {e}")
        return False

async def test_api_manager():
    """Test Universal API Manager"""
    print(f"\n🔑 TESTING UNIVERSAL API MANAGER")
    print("=" * 50)
    
    try:
        from sync_utils import api_manager, UniversalAPIManager
        
        print(f"✅ Successfully imported Universal API Manager")
        print(f"🔧 Manager Name: {api_manager.name}")
        print(f"👤 User: {api_manager.user_name}")
        print(f"🏢 Organization: {api_manager.organization}")
        
        print(f"\n📝 Testing Credential Registration:")
        test_creds = {
            "api_key": "test_key_12345",
            "auth_type": "bearer"
        }
        
        success = api_manager.register_api_credentials("test_service", test_creds)
        print(f"  Registration Success: {'✅' if success else '❌'}")
        
        print(f"\n🔐 Testing Auth Headers:")
        headers = api_manager.get_auth_headers("test_service")
        print(f"  Headers Generated: {'✅' if headers else '❌'}")
        print(f"  Authorization Header: {'✅' if 'Authorization' in headers else '❌'}")
        print(f"  ZORA Headers: {'✅' if 'X-ZORA-User' in headers else '❌'}")
        
        print(f"\n🔍 Testing Credential Auto-Discovery:")
        discovered = api_manager.auto_discover_credentials()
        print(f"  Discovered Credentials: {len(discovered)}")
        for cred in discovered[:3]:  # Show first 3
            print(f"    🔑 {cred}")
        
        return True
        
    except Exception as e:
        print(f"❌ API Manager Test Error: {e}")
        return False

async def test_enhanced_repair_engine():
    """Test Enhanced Repair Engine"""
    print(f"\n🔧 TESTING ENHANCED REPAIR ENGINE")
    print("=" * 50)
    
    try:
        from sync_utils import repair_engine, ZoraRepairEngine
        
        print(f"✅ Successfully imported Enhanced Repair Engine")
        print(f"👤 User: {repair_engine.user_name}")
        print(f"🏢 Organization: {repair_engine.organization}")
        
        print(f"\n🔍 Testing Error Diagnosis:")
        test_errors = [
            Exception("API key authentication failed"),
            Exception("Connection timeout occurred"),
            Exception("Rate limit exceeded"),
            Exception("Unknown endpoint error")
        ]
        
        for i, error in enumerate(test_errors):
            diagnosis = repair_engine.diagnose_agent_failure(f"test_agent_{i}", error)
            strategy = diagnosis.get("repair_strategy", "unknown")
            severity = diagnosis.get("severity", "unknown")
            print(f"  Error {i+1}: {strategy} (severity: {severity})")
        
        print(f"\n🛠️ Testing Repair Attempts:")
        for i in range(2):
            try:
                success = await repair_engine.attempt_repair(f"test_agent_{i}", "api_key_refresh")
                status = "✅ Success" if success else "❌ Failed"
                print(f"  Repair Agent {i}: {status}")
            except Exception as e:
                print(f"  Repair Agent {i}: ❌ Error - {e}")
        
        return True
        
    except Exception as e:
        print(f"❌ Repair Engine Test Error: {e}")
        return False

if __name__ == "__main__":
    print("🚀 ZORA CORE UNIVERSAL CONNECTOR TEST SUITE")
    print(f"⏰ Test started at: {datetime.utcnow().isoformat()}Z")
    print()
    
    async def run_all_tests():
        test1_result = await test_universal_connector()
        test2_result = await test_api_manager()
        test3_result = await test_enhanced_repair_engine()
        
        print("\n" + "=" * 50)
        print("📊 TEST RESULTS SUMMARY:")
        print(f"  Universal Connector: {'✅ PASSED' if test1_result else '❌ FAILED'}")
        print(f"  API Manager: {'✅ PASSED' if test2_result else '❌ FAILED'}")
        print(f"  Enhanced Repair Engine: {'✅ PASSED' if test3_result else '❌ FAILED'}")
        
        if test1_result and test2_result and test3_result:
            print("\n🎉 ALL TESTS PASSED - UNIVERSAL CONNECTOR READY FOR ZORA CORE")
        else:
            print("\n⚠️ SOME TESTS FAILED - CHECK INTEGRATION")
        
        print(f"\n⏰ Test completed at: {datetime.utcnow().isoformat()}Z")
    
    asyncio.run(run_all_tests())
