# ZORA MODULE HEADER

"""
Module Name: zora_contact_config
Generated by ZORA SYSTEM – All rights reserved.
INFINITY INJEKTION™ - Universal Contact Information System
Permanent integration across all ZORA CORE web properties
"""

import json
from typing import Dict, Any, Optional

ZORA_CONTACT_INFO = {
    "headquarters": {
        "name": "ZORA HQ",
        "address": "Fjordbakken 50, Dyves Bro, 4700 Næstved",
        "cvr": "37750514",
        "country": "Denmark",
        "postal_code": "4700",
        "city": "Næstved"
    },
    "p_enheder": {
        "structure": "KOBBERHJØRNET x ORINGE",
        "kobberhjornet": {
            "name": "KOBBERHJØRNET",
            "address": "Teatergade 4, 4700 Næstved",
            "postal_code": "4700",
            "city": "Næstved",
            "type": "P-enhed"
        },
        "oringe": {
            "name": "ORINGE",
            "address": "Færgegaardsvej 15, 4760 Vordingborg",
            "postal_code": "4760", 
            "city": "Vordingborg",
            "type": "P-enhed"
        }
    },
    "contact": {
        "email": "kontakt@zoracore.dk",
        "email_translations": {
            "en": "Contact",
            "da": "Kontakt",
            "de": "Kontaktieren", 
            "fr": "Contacter",
            "es": "Contacto",
            "it": "Contatto",
            "sv": "Kontakt",
            "no": "Kontakt",
            "fi": "Ota yhteyttä",
            "nl": "Contact",
            "pl": "Kontakt"
        },
        "phone_base": "+45 2082 2450",
        "website": "https://zoracore.dk"
    },
    "legal": {
        "company_type": "ApS",
        "registration_country": "Denmark",
        "vat_number": "DK37750514",
        "founded": "2024",
        "legal_name": "ZORA CORE ApS"
    },
    "infinity_mode": {
        "auto_sync": True,
        "gdpr_compliant": True,
        "responsive_design": True,
        "multi_language": True,
        "universal_injection": True
    }
}

def get_localized_email_label(language: str = "en") -> str:
    """
    Get localized email label for the specified language
    
    Args:
        language: ISO 639-1 language code (e.g., 'en', 'da', 'de')
        
    Returns:
        Localized email label string
    """
    return ZORA_CONTACT_INFO["contact"]["email_translations"].get(language.lower(), "Contact")

def generate_phone_number(subdomain: str = "", geographic_area: str = "dk") -> str:
    """
    Generate phone number for specific subdomain/geographic area
    
    Args:
        subdomain: Subdomain identifier for customization
        geographic_area: Geographic area code (default: 'dk' for Denmark)
        
    Returns:
        Formatted phone number string
    """
    base_number = ZORA_CONTACT_INFO["contact"]["phone_base"]
    
    if subdomain:
        pass
    
    if geographic_area.lower() != "dk":
        pass
    
    return base_number

def get_headquarters_info() -> Dict[str, Any]:
    """Get complete headquarters information"""
    return ZORA_CONTACT_INFO["headquarters"].copy()

def get_p_enheder_info() -> Dict[str, Any]:
    """Get complete P-enheder information"""
    return ZORA_CONTACT_INFO["p_enheder"].copy()

def get_contact_info(language: str = "en") -> Dict[str, Any]:
    """
    Get complete contact information with localized labels
    
    Args:
        language: Language code for localization
        
    Returns:
        Dictionary with contact information and localized labels
    """
    contact_info = ZORA_CONTACT_INFO["contact"].copy()
    contact_info["email_label"] = get_localized_email_label(language)
    return contact_info

def get_legal_info() -> Dict[str, Any]:
    """Get complete legal/company information"""
    return ZORA_CONTACT_INFO["legal"].copy()

def get_full_contact_data(language: str = "en", subdomain: str = "") -> Dict[str, Any]:
    """
    Get complete contact data for INFINITY INJEKTION™
    
    Args:
        language: Language code for localization
        subdomain: Subdomain for customization
        
    Returns:
        Complete contact data structure
    """
    return {
        "headquarters": get_headquarters_info(),
        "p_enheder": get_p_enheder_info(),
        "contact": {
            **get_contact_info(language),
            "phone": generate_phone_number(subdomain)
        },
        "legal": get_legal_info(),
        "infinity_mode": ZORA_CONTACT_INFO["infinity_mode"].copy(),
        "localization": {
            "language": language,
            "subdomain": subdomain
        }
    }

def export_contact_json(language: str = "en", subdomain: str = "") -> str:
    """
    Export contact information as JSON string
    
    Args:
        language: Language code for localization
        subdomain: Subdomain for customization
        
    Returns:
        JSON string with complete contact data
    """
    return json.dumps(get_full_contact_data(language, subdomain), indent=2, ensure_ascii=False)

def validate_contact_info() -> bool:
    """
    Validate that all required contact information is present
    
    Returns:
        True if all required fields are present, False otherwise
    """
    required_fields = [
        "headquarters.name",
        "headquarters.address", 
        "headquarters.cvr",
        "p_enheder.structure",
        "p_enheder.kobberhjornet.name",
        "p_enheder.kobberhjornet.address",
        "p_enheder.oringe.name",
        "p_enheder.oringe.address",
        "contact.email",
        "contact.phone_base"
    ]
    
    for field_path in required_fields:
        keys = field_path.split(".")
        current = ZORA_CONTACT_INFO
        
        try:
            for key in keys:
                current = current[key]
            if not current:
                return False
        except (KeyError, TypeError):
            return False
    
    return True

INFINITY_FOOTER_STRUCTURE = "KOBBERHJØRNET x ORINGE"
INFINITY_EMAIL = "kontakt@zoracore.dk"
INFINITY_CVR = "37750514"
INFINITY_HQ_ADDRESS = "Fjordbakken 50, Dyves Bro, 4700 Næstved"

def get_official_address_for_documents():
    """Get the official HQ address for emails, invoices, and legal documents"""
    hq = ZORA_CONTACT_INFO["headquarters"]
    return {
        "name": hq["name"],
        "address": hq["address"],
        "cvr": hq["cvr"],
        "country": hq["country"],
        "formatted_address": f"{hq['name']}\n{hq['address']}\nCVR: {hq['cvr']}\n{hq['country']}"
    }

def get_operational_addresses():
    """Get the daily operational addresses (KOBBERHJØRNET x ORINGE)"""
    p_enheder = ZORA_CONTACT_INFO["p_enheder"]
    return {
        "structure": p_enheder["structure"],
        "primary": {
            "name": p_enheder["kobberhjornet"]["name"],
            "address": p_enheder["kobberhjornet"]["address"],
            "type": "primary_operations"
        },
        "secondary": {
            "name": p_enheder["oringe"]["name"],
            "address": p_enheder["oringe"]["address"],
            "type": "secondary_operations"
        },
        "formatted_structure": f"{p_enheder['kobberhjornet']['name']}: {p_enheder['kobberhjornet']['address']}\n{p_enheder['oringe']['name']}: {p_enheder['oringe']['address']}"
    }

def generate_email_footer(language="da"):
    """Generate email footer with HQ address for all outgoing emails"""
    hq = get_official_address_for_documents()
    ops = get_operational_addresses()
    
    email_labels = {
        "da": {
            "hq_label": "Hovedkontor",
            "operations_label": "Daglige aktiviteter",
            "contact_label": "Kontakt"
        },
        "en": {
            "hq_label": "Headquarters", 
            "operations_label": "Daily Operations",
            "contact_label": "Contact"
        },
        "de": {
            "hq_label": "Hauptsitz",
            "operations_label": "Tägliche Operationen", 
            "contact_label": "Kontakt"
        },
        "fr": {
            "hq_label": "Siège social",
            "operations_label": "Opérations quotidiennes",
            "contact_label": "Contact"
        }
    }
    
    labels = email_labels.get(language, email_labels["da"])
    
    return f"""
---
{labels['hq_label']}: {hq['name']}
{hq['address']}
CVR: {hq['cvr']}

{labels['operations_label']}: {ops['structure']}
{ops['formatted_structure']}

{labels['contact_label']}: {INFINITY_EMAIL}
"""

def generate_invoice_header():
    """Generate invoice header with official HQ address"""
    hq = get_official_address_for_documents()
    
    return {
        "company_name": hq["name"],
        "address": hq["address"],
        "cvr": hq["cvr"],
        "country": hq["country"],
        "email": INFINITY_EMAIL,
        "formatted_header": f"""
{hq['name']}
{hq['address']}
CVR: {hq['cvr']}
{hq['country']}

Email: {INFINITY_EMAIL}
"""
    }

if __name__ == "__main__":
    print("🌐 ZORA INFINITY CONTACT CONFIGURATION")
    print("=" * 50)
    
    if validate_contact_info():
        print("✅ Contact configuration validation passed")
    else:
        print("❌ Contact configuration validation failed")
    
    print(f"🏢 HQ: {INFINITY_HQ_ADDRESS}")
    print(f"📧 Email: {INFINITY_EMAIL}")
    print(f"🏛️ CVR: {INFINITY_CVR}")
    print(f"📍 Structure: {INFINITY_FOOTER_STRUCTURE}")
    
    print("\n🌍 Language Support:")
    for lang_code in ["en", "da", "de", "fr", "es"]:
        label = get_localized_email_label(lang_code)
        print(f"   {lang_code.upper()}: {label}")
    
    print("\n♾️ INFINITY INJEKTION™ Configuration Ready")
