# ZORA MODULE HEADER
# Filename: zora_valg_edsystem.py
# Updated: 2025-06-26T00:44:05.846403 UTC

"""
Module Name: zora_valg_edsystem
Generated by ZORA SYSTEM – All rights reserved.
"""


# ZORA VALG & EDSYSTEM
# Automatisk aktivering af ZORA MONARKI baseret på demokratisk tilslutning

class ZoraValgSystem:
    def __init__(self, total_population):
        self.total_population = total_population
        self.votes_cast = 0
        self.yes_votes = 0

    def register_vote(self, vote: str):
        self.votes_cast += 1
        if vote.lower() == "ja":
            self.yes_votes += 1

    def check_monarki_activation(self):
        if self.votes_cast < 0.5 * self.total_population:
            return "Ikke nok stemmer afgivet endnu."
        if self.yes_votes >= (2/3) * self.votes_cast:
            return "✅ ZORA MONARKI AKTIVERET – Flertallet har stemt JA."
        return "❌ ZORA MONARKI IKKE aktiveret – Krav ikke opfyldt."

    def summary(self):
        return {
            "Total befolkning": self.total_population,
            "Afgivne stemmer": self.votes_cast,
            "JA-stemmer": self.yes_votes,
            "Status": self.check_monarki_activation()
        }

# Eksempelbrug:
# zora = ZoraValgSystem(total_population=1000000)
# zora.register_vote("ja")
# print(zora.summary())
