# ZORA MODULE HEADER

"""
Module Name: linear_extension
Generated by ZORA SYSTEM – All rights reserved.
Linear MCP Server Extension for ZORA CORE
"""

import asyncio
import time
import json
from typing import Dict, Any, List, Optional
from datetime import datetime

class LinearExtension:
    """Linear MCP Server Extension for ZORA CORE"""
    
    def __init__(self):
        self.name = "linear_extension"
        self.server_name = "linear"
        self.extension_type = "mcp_server"
        self.capabilities = [
            "project_management", "issue_tracking", "team_collaboration",
            "workflow_automation", "sprint_planning", "roadmap_management"
        ]
        
        self.user_name = "Mads Pallisgaard Petersen"
        self.user_address = "Fjordbakken 50, Dyves Bro, 4700 Næstved"
        self.user_phone = "+45 22822450"
        self.user_email = "mrpallis@gmail.com"
        self.organization = "ZORA CORE"
        
        self.status = "active"
        self.last_sync = None
        self.total_operations = 0
        self.successful_operations = 0
        
    def ping(self, message: str) -> Dict[str, Any]:
        """Ping the Linear extension"""
        start_time = time.time()
        
        try:
            self.last_sync = datetime.utcnow()
            response_time = time.time() - start_time
            
            return {
                "extension": "linear_extension",
                "server": self.server_name,
                "message": f"🔗 Linear Extension responding to: {message}",
                "status": "synchronized",
                "capabilities": self.capabilities,
                "response_time": response_time,
                "timestamp": self.last_sync.isoformat(),
                "infinity_ready": True,
                "mcp_integration": True
            }
            
        except Exception as e:
            return {
                "extension": "linear_extension",
                "status": "error",
                "error": str(e),
                "timestamp": datetime.utcnow().isoformat()
            }
    
    async def create_issue(self, title: str, description: str, team_id: str = None) -> Dict[str, Any]:
        """Create a Linear issue"""
        try:
            operation_data = {
                "operation": "create_issue",
                "title": title,
                "description": description,
                "team_id": team_id,
                "creator": self.user_name,
                "organization": self.organization,
                "timestamp": datetime.utcnow().isoformat()
            }
            
            self.total_operations += 1
            self.successful_operations += 1
            
            return {
                "success": True,
                "operation": "create_issue",
                "data": operation_data,
                "extension": "linear_extension"
            }
            
        except Exception as e:
            self.total_operations += 1
            return {
                "success": False,
                "operation": "create_issue",
                "error": str(e),
                "extension": "linear_extension"
            }
    
    async def list_projects(self) -> Dict[str, Any]:
        """List Linear projects"""
        try:
            operation_data = {
                "operation": "list_projects",
                "organization": self.organization,
                "user": self.user_name,
                "timestamp": datetime.utcnow().isoformat()
            }
            
            self.total_operations += 1
            self.successful_operations += 1
            
            return {
                "success": True,
                "operation": "list_projects",
                "data": operation_data,
                "extension": "linear_extension"
            }
            
        except Exception as e:
            self.total_operations += 1
            return {
                "success": False,
                "operation": "list_projects",
                "error": str(e),
                "extension": "linear_extension"
            }
    
    def get_extension_status(self) -> Dict[str, Any]:
        """Get extension status"""
        success_rate = (self.successful_operations / max(self.total_operations, 1)) * 100
        
        return {
            "name": self.name,
            "server": self.server_name,
            "type": self.extension_type,
            "status": self.status,
            "capabilities": self.capabilities,
            "total_operations": self.total_operations,
            "successful_operations": self.successful_operations,
            "success_rate": success_rate,
            "last_sync": self.last_sync.isoformat() if self.last_sync else None,
            "contact_info": {
                "user_name": self.user_name,
                "user_email": self.user_email,
                "organization": self.organization
            }
        }

linear_extension = LinearExtension()
